### PR TITLE
GWTIIRAR-23: documentation copied from documentation project.

### PR DESCRIPTION
**Pull request by janvenstermans**
Look at the documentation in the branch start page:
https://github.com/geomajas/geomajas-gwt2-quickstart-application/tree/JV_GWTIIRAR-23_documentationInMarkdown

compare with http://files.geomajas.org/enduser-application-gwt2/doc/master.html

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
+1 (binding)

**Comment by jandm** [comment]
+1 (binding)

**Comment by janvenstermans** [comment]
Vote count: 
Oliver May: +1 (binding)
Jan De Moerloose: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
