### PR TITLE
MAJ-1156_update copyright issues for all documentation module in all Geomajas projects

### PR DESCRIPTION
**Pull request by streulma**

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by jandm** [comment]
+1 (binding)

**Comment by janvenstermans** [comment]
Vote Successfull:
Oliver May: +1 (binding)
Jan De Moerloose: +1 (binding)

Jan Venstermans: +1

**Pull request merged**
